import { Character} from "./character";

export const CHLORR: Character = {
  name: 'Chlorr',
  level: 1,
  class: 'Fighter',
  race: 'Human',
  age: 21,
  sex: 'Female',
  profession: 'Dog Leech',
  origin: 'Coldwater / Cintra',
  alignment: 'Neutral',
  height: 68,
  weight: 140,
  eye_color: 'Light Amber',
  hair_color: 'Dark Brown',
  hair_style: 'Straight',
  hair_length: 'Bald',
  skin_color: 'Golden',
  hit_dice: 1,
  hit_dice_bonus: 1,
  current_hp: 6,
  total_hp: 7,
  armor_class: 7,
  melee_th_base: 1,
  melee_th_bonus: 1,
  missile_th_base: 1,
  missile_th_bonus: 1,
};
